### ISSUE TITLE
Improve @jahir system

### ISSUE THREAD

**Issue by justinkruit** [jahirfiquitiva/dashbot#3]
It seems like you can detect if the message is a reply using the `Message#reference` system, as it's the same for replies and crossposts. 

Docs: 
https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=reference
https://discord.js.org/#/docs/main/stable/typedef/MessageReference

**Comment by jahirfiquitiva** [comment]
@justinkruit Added some code for this, but I don't know what the plans were 😅
https://github.com/jahirfiquitiva/dashbot/blob/main/discord.js#L39=

<blockquote><img src="https://opengraph.githubassets.com/363ee5ff8dd8b87c64ba71fe5bc259caeb4df12e7742d59291f18aafbcbbcfe3/jahirfiquitiva/dashbot" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jahirfiquitiva/dashbot">dashbot/discord.js at main · jahirfiquitiva/dashbot</a></strong></div><div>A discord bot for my dashboards support server. Contribute to jahirfiquitiva/dashbot development by creating an account on GitHub.</div></blockquote>

**Comment by jahirfiquitiva** [comment]
there's also a bunch of deprecated methods, if you could help me update them, i'd really appreciate it 🙌

**Comment by justinkruit** [comment]
Sure thing! I hopefully can find some time soon to help update it.
